### PR TITLE
png -> webp

### PR DESCRIPTION
**Pull request by pocc**
# Commit 1: png -> webp
[webp](https://developers.google.com/speed/webp/) is an image format made by google for the web. This conversion will decrease loadtimes.

My [shell script](https://gist.github.com/pocc/908b3ecec33ae687372d8a25f8eca43c) that accomplished this. **cwebp**, the webp converter, can be installed on macos with `brew install webp`.

## png -> webp
* By converting your png images to webp, I've decreased the size of static/ by 16%. This will correspondingly make pageloads faster. Note that all of this was a completely lossless conversion. If you wanted to play around with further decreasing the size, use `cwebp -q $% <file> -o <file.webp>`, where $% is less than 100.
* I noticed that some images are loaded by S3. If you approve of these conversions, you will want to add these files / convert files in S3 to webp to realize these gains.

## png references -> webp references
* I've regexed png to webp so that nothing points to the old png files.

# Commit 2: Mostly cleanup
* Remove .DS_Store and add that pattern to .gitignore. This is a macOS folder metadata file.
* Added contributors from the github repo to the README.md. It may make more sense to list only project contributors who have made more than one commit or provide a link to the contributors page, but I leave that decision to you.

### CODE REVIEW

**Comment by elliotforbes** [comment]
Thanks for highlighting this! I can't merge this yet as I need to convert the CDN images to this format, I'll hopefully get this done and tested tomorrow when I find a good source of internet! :D

**Comment by pocc** [comment]
Yeah no problem - cheers on how fast you respond to these pull requests. I didn't touch the JPGs as you reference the files themselves as part of some of your AI articles, but you'd see gains for those as well if you converted them.

**Comment by elliotforbes** [comment]
I've moved the webp files you generated to the image.tutorialedge.net image CDN and I've added post-fetching for images which only loads the image after the content has been returned. This hacky script looks at browser version and replaces the file extension based on if it's safari or another browser:

```js
        function init() {
	        var imgDefer = document.getElementsByTagName('img');

		var ua = navigator.userAgent.toLowerCase(); 
		if (ua.indexOf('safari') != -1) { 
			if (ua.indexOf('chrome') > -1) {
				for (var i = 0; i < imgDefer.length; i++) {
					if (imgDefer[i].getAttribute('data-src')) {
						imgDefer[i].setAttribute('src',imgDefer[i].getAttribute('data-src') + ".webp");
					}
				} 
			} else {
				for (var i = 0; i < imgDefer.length; i++) {
					if (imgDefer[i].getAttribute('data-src')) {
						imgDefer[i].setAttribute('src',imgDefer[i].getAttribute('data-src') + ".png");
					}
				}
			}
		} else {
			for (var i = 0; i < imgDefer.length; i++) {
				if (imgDefer[i].getAttribute('data-src')) {
					imgDefer[i].setAttribute('src',imgDefer[i].getAttribute('data-src') + ".png");
				}
			}
		}
	}
	
	window.onload = init;
```

**Comment by pocc** [comment]
It sounds like you're addressing the issue for the pull request, so I'm happy to close.

**Comment by elliotforbes** [comment]
awesome, I seriously appreciate the help pointing me towards WebP! I now need to see if there are any other ways to optimize the site and get it to a 100/100 performance score on Lighthouse!

**Pull request closed without merging**
